// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rs2_rent_sistem.Services.Data;

#nullable disable

namespace rs2_rent_sistem.Services.Migrations
{
    [DbContext(typeof(RentSistemDbContext))]
    [Migration("20250117001013_AddIsDeletedToManufacturer")]
    partial class AddIsDeletedToManufacturer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Cart__3214EC27F092848C");

                    b.HasIndex("UserID");

                    b.ToTable("Cart", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4514),
                            TotalPrice = 45.75m,
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4520),
                            TotalPrice = 120.00m,
                            UserID = 3
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4522),
                            TotalPrice = 65.30m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4524),
                            TotalPrice = 78.40m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4526),
                            TotalPrice = 52.10m,
                            UserID = 6
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2025, 1, 16, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4529),
                            TotalPrice = 98.25m,
                            UserID = 7
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4531),
                            TotalPrice = 36.60m,
                            UserID = 8
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CartID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("ID")
                        .HasName("PK__CartItem__3214EC270170661E");

                    b.HasIndex("CartID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("CartItem", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CartID = 1,
                            EndDate = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4556),
                            EquipmentID = 1,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4553)
                        },
                        new
                        {
                            ID = 2,
                            CartID = 1,
                            EndDate = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4561),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4560)
                        },
                        new
                        {
                            ID = 3,
                            CartID = 2,
                            EndDate = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4565),
                            EquipmentID = 3,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4563)
                        },
                        new
                        {
                            ID = 4,
                            CartID = 3,
                            EndDate = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4568),
                            EquipmentID = 1,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4567)
                        },
                        new
                        {
                            ID = 5,
                            CartID = 3,
                            EndDate = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4571),
                            EquipmentID = 2,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4570)
                        },
                        new
                        {
                            ID = 6,
                            CartID = 4,
                            EndDate = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4575),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4574)
                        },
                        new
                        {
                            ID = 7,
                            CartID = 4,
                            EndDate = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4578),
                            EquipmentID = 3,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4577)
                        },
                        new
                        {
                            ID = 8,
                            CartID = 5,
                            EndDate = new DateTime(2025, 1, 16, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4581),
                            EquipmentID = 1,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4580)
                        },
                        new
                        {
                            ID = 9,
                            CartID = 6,
                            EndDate = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4585),
                            EquipmentID = 3,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 16, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4583)
                        },
                        new
                        {
                            ID = 10,
                            CartID = 7,
                            EndDate = new DateTime(2025, 1, 18, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4588),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4587)
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPerUse")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("int");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Equipmen__3214EC27E5E8D640");

                    b.HasIndex("AddedByUserID");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedByUserID = 1,
                            CostPerUse = 2.99m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3596),
                            Description = "Official size and weight.",
                            EquipmentCategoryId = 1,
                            ImageUrl = "soccerball.jpg",
                            IsDeleted = false,
                            ItemName = "Soccer Ball",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            ID = 2,
                            AddedByUserID = 1,
                            CostPerUse = 3.49m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3641),
                            Description = "High-quality leather basketball.",
                            EquipmentCategoryId = 2,
                            ImageUrl = "basketball.jpg",
                            IsDeleted = false,
                            ItemName = "Basketball",
                            ManufacturerID = 2,
                            MaxQuantity = 40,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 3,
                            AddedByUserID = 1,
                            CostPerUse = 4.99m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3646),
                            Description = "Lightweight racket for professional use.",
                            EquipmentCategoryId = 3,
                            ImageUrl = "tennisracket.jpg",
                            IsDeleted = false,
                            ItemName = "Tennis Racket",
                            ManufacturerID = 3,
                            MaxQuantity = 25,
                            MinQuantity = 2,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 4,
                            AddedByUserID = 1,
                            CostPerUse = 8.19m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3720),
                            Description = "Description for Equipment 4",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment4.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 4",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 37
                        },
                        new
                        {
                            ID = 5,
                            AddedByUserID = 1,
                            CostPerUse = 1.99m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3732),
                            Description = "Description for Equipment 5",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment5.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 5",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 32
                        },
                        new
                        {
                            ID = 6,
                            AddedByUserID = 1,
                            CostPerUse = 3.86m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3742),
                            Description = "Description for Equipment 6",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment6.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 6",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 33
                        },
                        new
                        {
                            ID = 7,
                            AddedByUserID = 1,
                            CostPerUse = 1.96m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3751),
                            Description = "Description for Equipment 7",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment7.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 7",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 19
                        },
                        new
                        {
                            ID = 8,
                            AddedByUserID = 1,
                            CostPerUse = 5.58m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3760),
                            Description = "Description for Equipment 8",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment8.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 8",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 36
                        },
                        new
                        {
                            ID = 9,
                            AddedByUserID = 1,
                            CostPerUse = 6.84m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3769),
                            Description = "Description for Equipment 9",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment9.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 9",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 45
                        },
                        new
                        {
                            ID = 10,
                            AddedByUserID = 1,
                            CostPerUse = 1.19m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3778),
                            Description = "Description for Equipment 10",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment10.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 10",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 16
                        },
                        new
                        {
                            ID = 11,
                            AddedByUserID = 1,
                            CostPerUse = 1.15m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3787),
                            Description = "Description for Equipment 11",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment11.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 11",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 12,
                            AddedByUserID = 1,
                            CostPerUse = 7.77m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3795),
                            Description = "Description for Equipment 12",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment12.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 12",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 39
                        },
                        new
                        {
                            ID = 13,
                            AddedByUserID = 1,
                            CostPerUse = 5.92m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3860),
                            Description = "Description for Equipment 13",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment13.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 13",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 40
                        },
                        new
                        {
                            ID = 14,
                            AddedByUserID = 1,
                            CostPerUse = 8.13m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3869),
                            Description = "Description for Equipment 14",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment14.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 14",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 39
                        },
                        new
                        {
                            ID = 15,
                            AddedByUserID = 1,
                            CostPerUse = 4.32m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3878),
                            Description = "Description for Equipment 15",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment15.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 15",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 16,
                            AddedByUserID = 1,
                            CostPerUse = 4.04m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3886),
                            Description = "Description for Equipment 16",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment16.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 16",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 32
                        },
                        new
                        {
                            ID = 17,
                            AddedByUserID = 1,
                            CostPerUse = 9.29m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3895),
                            Description = "Description for Equipment 17",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment17.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 17",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 12
                        },
                        new
                        {
                            ID = 18,
                            AddedByUserID = 1,
                            CostPerUse = 2.42m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3904),
                            Description = "Description for Equipment 18",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment18.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 18",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 34
                        },
                        new
                        {
                            ID = 19,
                            AddedByUserID = 1,
                            CostPerUse = 1.24m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3913),
                            Description = "Description for Equipment 19",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment19.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 19",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 10
                        },
                        new
                        {
                            ID = 20,
                            AddedByUserID = 1,
                            CostPerUse = 4.30m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3921),
                            Description = "Description for Equipment 20",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment20.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 20",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 13
                        },
                        new
                        {
                            ID = 21,
                            AddedByUserID = 1,
                            CostPerUse = 4.18m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3929),
                            Description = "Description for Equipment 21",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment21.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 21",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 33
                        },
                        new
                        {
                            ID = 22,
                            AddedByUserID = 1,
                            CostPerUse = 4.37m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3937),
                            Description = "Description for Equipment 22",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment22.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 22",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 37
                        },
                        new
                        {
                            ID = 23,
                            AddedByUserID = 1,
                            CostPerUse = 8.63m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3945),
                            Description = "Description for Equipment 23",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment23.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 23",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            ID = 24,
                            AddedByUserID = 1,
                            CostPerUse = 3.62m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3981),
                            Description = "Description for Equipment 24",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment24.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 24",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 25,
                            AddedByUserID = 1,
                            CostPerUse = 7.67m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3990),
                            Description = "Description for Equipment 25",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment25.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 25",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 49
                        },
                        new
                        {
                            ID = 26,
                            AddedByUserID = 1,
                            CostPerUse = 6.30m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(3999),
                            Description = "Description for Equipment 26",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment26.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 26",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 27,
                            AddedByUserID = 1,
                            CostPerUse = 3.13m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4008),
                            Description = "Description for Equipment 27",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment27.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 27",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 48
                        },
                        new
                        {
                            ID = 28,
                            AddedByUserID = 1,
                            CostPerUse = 5.44m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4016),
                            Description = "Description for Equipment 28",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment28.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 28",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        },
                        new
                        {
                            ID = 29,
                            AddedByUserID = 1,
                            CostPerUse = 7.09m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4025),
                            Description = "Description for Equipment 29",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment29.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 29",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 43
                        },
                        new
                        {
                            ID = 30,
                            AddedByUserID = 1,
                            CostPerUse = 5.54m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4033),
                            Description = "Description for Equipment 30",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment30.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 30",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 34
                        },
                        new
                        {
                            ID = 31,
                            AddedByUserID = 1,
                            CostPerUse = 8.04m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4042),
                            Description = "Description for Equipment 31",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment31.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 31",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 45
                        },
                        new
                        {
                            ID = 32,
                            AddedByUserID = 1,
                            CostPerUse = 1.88m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4050),
                            Description = "Description for Equipment 32",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment32.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 32",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 47
                        },
                        new
                        {
                            ID = 33,
                            AddedByUserID = 1,
                            CostPerUse = 5.97m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4059),
                            Description = "Description for Equipment 33",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment33.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 33",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 19
                        },
                        new
                        {
                            ID = 34,
                            AddedByUserID = 1,
                            CostPerUse = 8.36m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4068),
                            Description = "Description for Equipment 34",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment34.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 34",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 24
                        },
                        new
                        {
                            ID = 35,
                            AddedByUserID = 1,
                            CostPerUse = 0.66m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4104),
                            Description = "Description for Equipment 35",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment35.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 35",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 29
                        },
                        new
                        {
                            ID = 36,
                            AddedByUserID = 1,
                            CostPerUse = 2.67m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4113),
                            Description = "Description for Equipment 36",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment36.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 36",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 32
                        },
                        new
                        {
                            ID = 37,
                            AddedByUserID = 1,
                            CostPerUse = 0.21m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4121),
                            Description = "Description for Equipment 37",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment37.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 37",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 47
                        },
                        new
                        {
                            ID = 38,
                            AddedByUserID = 1,
                            CostPerUse = 8.80m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4130),
                            Description = "Description for Equipment 38",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment38.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 38",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 39,
                            AddedByUserID = 1,
                            CostPerUse = 2.83m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4138),
                            Description = "Description for Equipment 39",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment39.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 39",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 37
                        },
                        new
                        {
                            ID = 40,
                            AddedByUserID = 1,
                            CostPerUse = 6.46m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4147),
                            Description = "Description for Equipment 40",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment40.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 40",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 41,
                            AddedByUserID = 1,
                            CostPerUse = 2.74m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4155),
                            Description = "Description for Equipment 41",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment41.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 41",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        },
                        new
                        {
                            ID = 42,
                            AddedByUserID = 1,
                            CostPerUse = 1.42m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4163),
                            Description = "Description for Equipment 42",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment42.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 42",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 34
                        },
                        new
                        {
                            ID = 43,
                            AddedByUserID = 1,
                            CostPerUse = 8.13m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4173),
                            Description = "Description for Equipment 43",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment43.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 43",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 40
                        },
                        new
                        {
                            ID = 44,
                            AddedByUserID = 1,
                            CostPerUse = 6.86m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4181),
                            Description = "Description for Equipment 44",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment44.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 44",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 45,
                            AddedByUserID = 1,
                            CostPerUse = 6.22m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4190),
                            Description = "Description for Equipment 45",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment45.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 45",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 36
                        },
                        new
                        {
                            ID = 46,
                            AddedByUserID = 1,
                            CostPerUse = 9.61m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4225),
                            Description = "Description for Equipment 46",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment46.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 46",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        },
                        new
                        {
                            ID = 47,
                            AddedByUserID = 1,
                            CostPerUse = 9.96m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4233),
                            Description = "Description for Equipment 47",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment47.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 47",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            ID = 48,
                            AddedByUserID = 1,
                            CostPerUse = 8.31m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4241),
                            Description = "Description for Equipment 48",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment48.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 48",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 22
                        },
                        new
                        {
                            ID = 49,
                            AddedByUserID = 1,
                            CostPerUse = 6.28m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4250),
                            Description = "Description for Equipment 49",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment49.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 49",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 50,
                            AddedByUserID = 1,
                            CostPerUse = 0.82m,
                            DateAdded = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4258),
                            Description = "Description for Equipment 50",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment50.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 50",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 23
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.EquipmentCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID")
                        .HasName("PK__Equipmen__3214EC2767D63CD6");

                    b.ToTable("EquipmentCategory", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Equipment for football and soccer",
                            Name = "Football"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Basketball equipment and accessories",
                            Name = "Basketball"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Tennis rackets and gear",
                            Name = "Tennis"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Baseball bats, gloves, and equipment",
                            Name = "Baseball"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Bikes and cycling gear",
                            Name = "Cycling"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Running shoes and accessories",
                            Name = "Running"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Swimming gear and equipment",
                            Name = "Swimming"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Golf clubs and accessories",
                            Name = "Golf"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Boxing gloves and equipment",
                            Name = "Boxing"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Fitness and gym equipment",
                            Name = "Fitness"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID")
                        .HasName("PK__Manufact__3214EC279512E539");

                    b.ToTable("Manufacturer", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Sportswear and equipment manufacturer",
                            IsDeleted = false,
                            Name = "Nike"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Global sports equipment manufacturer",
                            IsDeleted = false,
                            Name = "Adidas"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Sporting goods and apparel manufacturer",
                            IsDeleted = false,
                            Name = "Puma"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Performance apparel and gear",
                            IsDeleted = false,
                            Name = "Under Armour"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Footwear and sports equipment",
                            IsDeleted = false,
                            Name = "Reebok"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Sports equipment, especially in tennis",
                            IsDeleted = false,
                            Name = "Wilson"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Basketball and sporting goods manufacturer",
                            IsDeleted = false,
                            Name = "Spalding"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Badminton and tennis equipment manufacturer",
                            IsDeleted = false,
                            Name = "Yonex"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Golf equipment and accessories",
                            IsDeleted = false,
                            Name = "Callaway"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Boxing equipment and apparel manufacturer",
                            IsDeleted = false,
                            Name = "Everlast"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DatePlaced")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Order__3214EC27E334F241");

                    b.HasIndex("UserID");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DatePlaced = new DateTime(2025, 1, 7, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4334),
                            IsActive = true,
                            TotalPrice = 59.94m,
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            DatePlaced = new DateTime(2025, 1, 9, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4337),
                            IsActive = true,
                            TotalPrice = 89.85m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            DatePlaced = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4340),
                            IsActive = true,
                            TotalPrice = 29.97m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            DatePlaced = new DateTime(2025, 1, 10, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4342),
                            IsActive = true,
                            TotalPrice = 19.98m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            DatePlaced = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4344),
                            IsActive = true,
                            TotalPrice = 99.90m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 6,
                            DatePlaced = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4346),
                            IsActive = true,
                            TotalPrice = 49.95m,
                            UserID = 6
                        },
                        new
                        {
                            ID = 7,
                            DatePlaced = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4348),
                            IsActive = true,
                            TotalPrice = 69.93m,
                            UserID = 7
                        },
                        new
                        {
                            ID = 8,
                            DatePlaced = new DateTime(2025, 1, 16, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4350),
                            IsActive = true,
                            TotalPrice = 39.96m,
                            UserID = 8
                        },
                        new
                        {
                            ID = 9,
                            DatePlaced = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4352),
                            IsActive = true,
                            TotalPrice = 149.85m,
                            UserID = 9
                        },
                        new
                        {
                            ID = 10,
                            DatePlaced = new DateTime(2025, 1, 8, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4354),
                            IsActive = true,
                            TotalPrice = 29.97m,
                            UserID = 10
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("CostPerUse")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("ID")
                        .HasName("PK__OrderIte__3214EC27A60ECC1F");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 8, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4409),
                            EquipmentID = 1,
                            OrderID = 1,
                            Price = 5.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 7, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4406)
                        },
                        new
                        {
                            ID = 2,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 9, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4416),
                            EquipmentID = 3,
                            OrderID = 1,
                            Price = 4.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 7, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4415)
                        },
                        new
                        {
                            ID = 3,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 10, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4420),
                            EquipmentID = 2,
                            OrderID = 2,
                            Price = 10.47m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 9, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4419)
                        },
                        new
                        {
                            ID = 4,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4425),
                            EquipmentID = 1,
                            OrderID = 2,
                            Price = 11.96m,
                            Quantity = 4,
                            StartDate = new DateTime(2025, 1, 9, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4423)
                        },
                        new
                        {
                            ID = 5,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4428),
                            EquipmentID = 3,
                            OrderID = 3,
                            Price = 9.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4427)
                        },
                        new
                        {
                            ID = 6,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4434),
                            EquipmentID = 1,
                            OrderID = 4,
                            Price = 2.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 10, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4433)
                        },
                        new
                        {
                            ID = 7,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4465),
                            EquipmentID = 2,
                            OrderID = 5,
                            Price = 17.45m,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4463)
                        },
                        new
                        {
                            ID = 8,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 16, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4469),
                            EquipmentID = 3,
                            OrderID = 6,
                            Price = 14.97m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 14, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4467)
                        },
                        new
                        {
                            ID = 9,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 18, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4475),
                            EquipmentID = 1,
                            OrderID = 7,
                            Price = 5.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 15, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4472)
                        },
                        new
                        {
                            ID = 10,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 17, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4480),
                            EquipmentID = 2,
                            OrderID = 8,
                            Price = 10.47m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 16, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4478)
                        },
                        new
                        {
                            ID = 11,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 13, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4484),
                            EquipmentID = 3,
                            OrderID = 9,
                            Price = 4.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4482)
                        },
                        new
                        {
                            ID = 12,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 12, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4488),
                            EquipmentID = 1,
                            OrderID = 9,
                            Price = 14.95m,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 1, 11, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4486)
                        },
                        new
                        {
                            ID = 13,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 9, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4492),
                            EquipmentID = 2,
                            OrderID = 10,
                            Price = 6.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 8, 1, 10, 13, 367, DateTimeKind.Local).AddTicks(4491)
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal?>("NumberOfStars")
                        .HasColumnType("decimal(1, 1)");

                    b.Property<int?>("OrderItemID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Review__3214EC273729A687");

                    b.HasIndex("AddedByUserID");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Role__3214EC2778B20863");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Radnik u rent biznisu, koristi desktop app",
                            Name = "employee"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Krajnji korisnik, koristi mobilnu aplikaciju",
                            Name = "end-user"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Salt")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID")
                        .HasName("PK__User__3214EC278C534519");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "una.belko+radnik@edu.fit.ba",
                            FirstName = "Una",
                            IsActive = true,
                            LastName = "Radnik",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "0038763222111",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 2,
                            Email = "una.belko+shopping@edu.fit.ba",
                            FirstName = "Una",
                            IsActive = true,
                            LastName = "Shopping",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "0038763222111",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 3,
                            Email = "michael.johnson+user@rental.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-8765",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 4,
                            Email = "emily.davis+user@rental.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-4321",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 5,
                            Email = "william.brown+user@rental.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-6789",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 6,
                            Email = "ava.wilson+user@rental.com",
                            FirstName = "Ava",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-2345",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 7,
                            Email = "james.taylor+user@rental.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-7890",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 8,
                            Email = "olivia.anderson+user@rental.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-3456",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 9,
                            Email = "benjamin.thomas+user@rental.com",
                            FirstName = "Benjamin",
                            IsActive = true,
                            LastName = "Thomas",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-9012",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        },
                        new
                        {
                            ID = 10,
                            Email = "sophia.moore+user@rental.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "Xy15y1hYepVg+ZP/YwZos14rgc/ph1Yde9BX6ExAVHk=",
                            Phone = "555-6543",
                            Salt = "2N07XEIzN4iKL7TpSz54QQ=="
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("datetime");

                    b.HasKey("UserID", "RoleID")
                        .HasName("PK__UserRole__AF27604F8443E939");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            UserID = 2,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 3,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 4,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 5,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 6,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 7,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 8,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 9,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 10,
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Cart__UserID__5535A963");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.CartItem", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .HasConstraintName("FK__CartItem__CartID__5812160E");

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", "Equipment")
                        .WithMany("CartItems")
                        .HasForeignKey("EquipmentID")
                        .HasConstraintName("FK__CartItem__Equipm__59063A47");

                    b.Navigation("Cart");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "AddedByUser")
                        .WithMany("Equipment")
                        .HasForeignKey("AddedByUserID")
                        .HasConstraintName("FK__Equipment__Added__44FF419A");

                    b.HasOne("rs2_rent_sistem.Services.Database.EquipmentCategory", "EquipmentCategory")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentCategoryId")
                        .HasConstraintName("FK__Equipment__Equip__45F365D3");

                    b.HasOne("rs2_rent_sistem.Services.Database.Manufacturer", "Manufacturer")
                        .WithMany("Equipment")
                        .HasForeignKey("ManufacturerID")
                        .HasConstraintName("FK__Equipment__Manuf__440B1D61");

                    b.Navigation("AddedByUser");

                    b.Navigation("EquipmentCategory");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Order__UserID__49C3F6B7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", "Equipment")
                        .WithMany("OrderItems")
                        .HasForeignKey("EquipmentID")
                        .HasConstraintName("FK__OrderItem__Equip__4D94879B");

                    b.HasOne("rs2_rent_sistem.Services.Database.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .HasConstraintName("FK__OrderItem__Order__4CA06362");

                    b.Navigation("Equipment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Review", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "AddedByUser")
                        .WithMany("Reviews")
                        .HasForeignKey("AddedByUserID")
                        .HasConstraintName("FK__Review__AddedByU__5070F446");

                    b.HasOne("rs2_rent_sistem.Services.Database.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemID")
                        .HasConstraintName("FK__Review__OrderIte__5165187F");

                    b.Navigation("AddedByUser");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.UserRole", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .IsRequired()
                        .HasConstraintName("FK__UserRole__RoleID__3D5E1FD2");

                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .IsRequired()
                        .HasConstraintName("FK__UserRole__UserID__3C69FB99");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Manufacturer", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Equipment");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
