// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rs2_rent_sistem.Services.Data;

#nullable disable

namespace rs2_rent_sistem.Services.Migrations
{
    [DbContext(typeof(RentSistemDbContext))]
    partial class RentSistemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4655),
                            TotalPrice = 45.75m,
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4658),
                            TotalPrice = 120.00m,
                            UserID = 3
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4660),
                            TotalPrice = 65.30m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4662),
                            TotalPrice = 78.40m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4664),
                            TotalPrice = 52.10m,
                            UserID = 6
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4666),
                            TotalPrice = 98.25m,
                            UserID = 7
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4667),
                            TotalPrice = 36.60m,
                            UserID = 8
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("EquipmentID1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("EquipmentID1");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CartID = 1,
                            EndDate = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4690),
                            EquipmentID = 1,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4683)
                        },
                        new
                        {
                            ID = 2,
                            CartID = 1,
                            EndDate = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4694),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4693)
                        },
                        new
                        {
                            ID = 3,
                            CartID = 2,
                            EndDate = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4696),
                            EquipmentID = 3,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4695)
                        },
                        new
                        {
                            ID = 4,
                            CartID = 3,
                            EndDate = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4699),
                            EquipmentID = 1,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4698)
                        },
                        new
                        {
                            ID = 5,
                            CartID = 3,
                            EndDate = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4701),
                            EquipmentID = 2,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4700)
                        },
                        new
                        {
                            ID = 6,
                            CartID = 4,
                            EndDate = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4704),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4703)
                        },
                        new
                        {
                            ID = 7,
                            CartID = 4,
                            EndDate = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4706),
                            EquipmentID = 3,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4705)
                        },
                        new
                        {
                            ID = 8,
                            CartID = 5,
                            EndDate = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4709),
                            EquipmentID = 1,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4708)
                        },
                        new
                        {
                            ID = 9,
                            CartID = 6,
                            EndDate = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4711),
                            EquipmentID = 3,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4710)
                        },
                        new
                        {
                            ID = 10,
                            CartID = 7,
                            EndDate = new DateTime(2025, 2, 6, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4714),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4713)
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Damage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Damages");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPerUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("int");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddedByUserID");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedByUserID = 1,
                            CostPerUse = 2.99m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3681),
                            Description = "Official size and weight.",
                            EquipmentCategoryId = 1,
                            ImageUrl = "soccerball.jpg",
                            IsDeleted = false,
                            ItemName = "Soccer Ball",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            ID = 2,
                            AddedByUserID = 1,
                            CostPerUse = 3.49m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3732),
                            Description = "High-quality leather basketball.",
                            EquipmentCategoryId = 2,
                            ImageUrl = "basketball.jpg",
                            IsDeleted = false,
                            ItemName = "Basketball",
                            ManufacturerID = 2,
                            MaxQuantity = 40,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 3,
                            AddedByUserID = 1,
                            CostPerUse = 4.99m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3765),
                            Description = "Lightweight racket for professional use.",
                            EquipmentCategoryId = 3,
                            ImageUrl = "tennisracket.jpg",
                            IsDeleted = false,
                            ItemName = "Tennis Racket",
                            ManufacturerID = 3,
                            MaxQuantity = 25,
                            MinQuantity = 2,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 4,
                            AddedByUserID = 1,
                            CostPerUse = 0.74m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3824),
                            Description = "Description for Equipment 4",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment4.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 4",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 25
                        },
                        new
                        {
                            ID = 5,
                            AddedByUserID = 1,
                            CostPerUse = 0.87m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3841),
                            Description = "Description for Equipment 5",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment5.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 5",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 6,
                            AddedByUserID = 1,
                            CostPerUse = 1.72m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3851),
                            Description = "Description for Equipment 6",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment6.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 6",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        },
                        new
                        {
                            ID = 7,
                            AddedByUserID = 1,
                            CostPerUse = 2.73m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3859),
                            Description = "Description for Equipment 7",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment7.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 7",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        },
                        new
                        {
                            ID = 8,
                            AddedByUserID = 1,
                            CostPerUse = 1.32m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3867),
                            Description = "Description for Equipment 8",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment8.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 8",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 45
                        },
                        new
                        {
                            ID = 9,
                            AddedByUserID = 1,
                            CostPerUse = 7.08m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3875),
                            Description = "Description for Equipment 9",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment9.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 9",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 13
                        },
                        new
                        {
                            ID = 10,
                            AddedByUserID = 1,
                            CostPerUse = 9.68m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3884),
                            Description = "Description for Equipment 10",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment10.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 10",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 48
                        },
                        new
                        {
                            ID = 11,
                            AddedByUserID = 1,
                            CostPerUse = 6.03m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3893),
                            Description = "Description for Equipment 11",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment11.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 11",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 47
                        },
                        new
                        {
                            ID = 12,
                            AddedByUserID = 1,
                            CostPerUse = 8.97m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3900),
                            Description = "Description for Equipment 12",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment12.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 12",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 23
                        },
                        new
                        {
                            ID = 13,
                            AddedByUserID = 1,
                            CostPerUse = 0.04m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3910),
                            Description = "Description for Equipment 13",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment13.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 13",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 28
                        },
                        new
                        {
                            ID = 14,
                            AddedByUserID = 1,
                            CostPerUse = 1.88m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3918),
                            Description = "Description for Equipment 14",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment14.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 14",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 15,
                            AddedByUserID = 1,
                            CostPerUse = 1.07m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3959),
                            Description = "Description for Equipment 15",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment15.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 15",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 23
                        },
                        new
                        {
                            ID = 16,
                            AddedByUserID = 1,
                            CostPerUse = 0.20m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3967),
                            Description = "Description for Equipment 16",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment16.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 16",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            ID = 17,
                            AddedByUserID = 1,
                            CostPerUse = 9.77m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3975),
                            Description = "Description for Equipment 17",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment17.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 17",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 14
                        },
                        new
                        {
                            ID = 18,
                            AddedByUserID = 1,
                            CostPerUse = 9.30m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3984),
                            Description = "Description for Equipment 18",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment18.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 18",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 21
                        },
                        new
                        {
                            ID = 19,
                            AddedByUserID = 1,
                            CostPerUse = 3.21m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3992),
                            Description = "Description for Equipment 19",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment19.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 19",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 34
                        },
                        new
                        {
                            ID = 20,
                            AddedByUserID = 1,
                            CostPerUse = 0.64m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(3999),
                            Description = "Description for Equipment 20",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment20.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 20",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 12
                        },
                        new
                        {
                            ID = 21,
                            AddedByUserID = 1,
                            CostPerUse = 1.40m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4008),
                            Description = "Description for Equipment 21",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment21.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 21",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 45
                        },
                        new
                        {
                            ID = 22,
                            AddedByUserID = 1,
                            CostPerUse = 3.87m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4015),
                            Description = "Description for Equipment 22",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment22.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 22",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 23,
                            AddedByUserID = 1,
                            CostPerUse = 7.28m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4023),
                            Description = "Description for Equipment 23",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment23.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 23",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 10
                        },
                        new
                        {
                            ID = 24,
                            AddedByUserID = 1,
                            CostPerUse = 5.10m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4031),
                            Description = "Description for Equipment 24",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment24.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 24",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 25,
                            AddedByUserID = 1,
                            CostPerUse = 6.14m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4039),
                            Description = "Description for Equipment 25",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment25.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 25",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 24
                        },
                        new
                        {
                            ID = 26,
                            AddedByUserID = 1,
                            CostPerUse = 7.08m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4065),
                            Description = "Description for Equipment 26",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment26.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 26",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 42
                        },
                        new
                        {
                            ID = 27,
                            AddedByUserID = 1,
                            CostPerUse = 6.05m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4073),
                            Description = "Description for Equipment 27",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment27.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 27",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 28,
                            AddedByUserID = 1,
                            CostPerUse = 3.85m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4081),
                            Description = "Description for Equipment 28",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment28.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 28",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 29,
                            AddedByUserID = 1,
                            CostPerUse = 9.41m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4089),
                            Description = "Description for Equipment 29",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment29.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 29",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 43
                        },
                        new
                        {
                            ID = 30,
                            AddedByUserID = 1,
                            CostPerUse = 9.54m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4097),
                            Description = "Description for Equipment 30",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment30.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 30",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 14
                        },
                        new
                        {
                            ID = 31,
                            AddedByUserID = 1,
                            CostPerUse = 7.30m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4104),
                            Description = "Description for Equipment 31",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment31.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 31",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 40
                        },
                        new
                        {
                            ID = 32,
                            AddedByUserID = 1,
                            CostPerUse = 7.15m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4112),
                            Description = "Description for Equipment 32",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment32.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 32",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 10
                        },
                        new
                        {
                            ID = 33,
                            AddedByUserID = 1,
                            CostPerUse = 0.19m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4120),
                            Description = "Description for Equipment 33",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment33.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 33",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 29
                        },
                        new
                        {
                            ID = 34,
                            AddedByUserID = 1,
                            CostPerUse = 4.11m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4128),
                            Description = "Description for Equipment 34",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment34.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 34",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 47
                        },
                        new
                        {
                            ID = 35,
                            AddedByUserID = 1,
                            CostPerUse = 3.78m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4136),
                            Description = "Description for Equipment 35",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment35.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 35",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 17
                        },
                        new
                        {
                            ID = 36,
                            AddedByUserID = 1,
                            CostPerUse = 0.06m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4144),
                            Description = "Description for Equipment 36",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment36.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 36",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 39
                        },
                        new
                        {
                            ID = 37,
                            AddedByUserID = 1,
                            CostPerUse = 3.45m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4173),
                            Description = "Description for Equipment 37",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment37.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 37",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 11
                        },
                        new
                        {
                            ID = 38,
                            AddedByUserID = 1,
                            CostPerUse = 0.17m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4180),
                            Description = "Description for Equipment 38",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment38.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 38",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 41
                        },
                        new
                        {
                            ID = 39,
                            AddedByUserID = 1,
                            CostPerUse = 3.43m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4188),
                            Description = "Description for Equipment 39",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment39.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 39",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 40,
                            AddedByUserID = 1,
                            CostPerUse = 3.45m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4196),
                            Description = "Description for Equipment 40",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment40.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 40",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 18
                        },
                        new
                        {
                            ID = 41,
                            AddedByUserID = 1,
                            CostPerUse = 7.28m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4204),
                            Description = "Description for Equipment 41",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment41.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 41",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 42,
                            AddedByUserID = 1,
                            CostPerUse = 5.70m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4212),
                            Description = "Description for Equipment 42",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment42.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 42",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 13
                        },
                        new
                        {
                            ID = 43,
                            AddedByUserID = 1,
                            CostPerUse = 4.05m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4220),
                            Description = "Description for Equipment 43",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment43.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 43",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 40
                        },
                        new
                        {
                            ID = 44,
                            AddedByUserID = 1,
                            CostPerUse = 3.00m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4227),
                            Description = "Description for Equipment 44",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment44.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 44",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 34
                        },
                        new
                        {
                            ID = 45,
                            AddedByUserID = 1,
                            CostPerUse = 0.67m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4235),
                            Description = "Description for Equipment 45",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment45.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 45",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 37
                        },
                        new
                        {
                            ID = 46,
                            AddedByUserID = 1,
                            CostPerUse = 6.61m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4309),
                            Description = "Description for Equipment 46",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment46.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 46",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 47,
                            AddedByUserID = 1,
                            CostPerUse = 6.11m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4317),
                            Description = "Description for Equipment 47",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment47.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 47",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 10
                        },
                        new
                        {
                            ID = 48,
                            AddedByUserID = 1,
                            CostPerUse = 0.77m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4345),
                            Description = "Description for Equipment 48",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment48.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 48",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 14
                        },
                        new
                        {
                            ID = 49,
                            AddedByUserID = 1,
                            CostPerUse = 1.48m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4352),
                            Description = "Description for Equipment 49",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment49.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 49",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 50,
                            AddedByUserID = 1,
                            CostPerUse = 8.23m,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4361),
                            Description = "Description for Equipment 50",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment50.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 50",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 41
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.EquipmentCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EquipmentCategories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Equipment for football and soccer",
                            IsDeleted = false,
                            Name = "Football"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Basketball equipment and accessories",
                            IsDeleted = false,
                            Name = "Basketball"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Tennis rackets and gear",
                            IsDeleted = false,
                            Name = "Tennis"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Baseball bats, gloves, and equipment",
                            IsDeleted = false,
                            Name = "Baseball"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Bikes and cycling gear",
                            IsDeleted = false,
                            Name = "Cycling"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Running shoes and accessories",
                            IsDeleted = false,
                            Name = "Running"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Swimming gear and equipment",
                            IsDeleted = false,
                            Name = "Swimming"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Golf clubs and accessories",
                            IsDeleted = false,
                            Name = "Golf"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Boxing gloves and equipment",
                            IsDeleted = false,
                            Name = "Boxing"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Fitness and gym equipment",
                            IsDeleted = false,
                            Name = "Fitness"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Sportswear and equipment manufacturer",
                            IsDeleted = false,
                            Name = "Nike"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Global sports equipment manufacturer",
                            IsDeleted = false,
                            Name = "Adidas"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Sporting goods and apparel manufacturer",
                            IsDeleted = false,
                            Name = "Puma"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Performance apparel and gear",
                            IsDeleted = false,
                            Name = "Under Armour"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Footwear and sports equipment",
                            IsDeleted = false,
                            Name = "Reebok"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Sports equipment, especially in tennis",
                            IsDeleted = false,
                            Name = "Wilson"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Basketball and sporting goods manufacturer",
                            IsDeleted = false,
                            Name = "Spalding"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Badminton and tennis equipment manufacturer",
                            IsDeleted = false,
                            Name = "Yonex"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Golf equipment and accessories",
                            IsDeleted = false,
                            Name = "Callaway"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Boxing equipment and apparel manufacturer",
                            IsDeleted = false,
                            Name = "Everlast"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatePlaced")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DatePlaced = new DateTime(2025, 1, 26, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4423),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 59.94m,
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            DatePlaced = new DateTime(2025, 1, 28, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4427),
                            IsActive = true,
                            Status = "paid",
                            TotalPrice = 89.85m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            DatePlaced = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4428),
                            IsActive = true,
                            Status = "rented",
                            TotalPrice = 29.97m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            DatePlaced = new DateTime(2025, 1, 29, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4430),
                            IsActive = true,
                            Status = "rented",
                            TotalPrice = 19.98m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            DatePlaced = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4432),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 99.90m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 6,
                            DatePlaced = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4433),
                            IsActive = true,
                            Status = "rented",
                            TotalPrice = 49.95m,
                            UserID = 6
                        },
                        new
                        {
                            ID = 7,
                            DatePlaced = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4435),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 69.93m,
                            UserID = 7
                        },
                        new
                        {
                            ID = 8,
                            DatePlaced = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4437),
                            IsActive = true,
                            Status = "paid",
                            TotalPrice = 39.96m,
                            UserID = 8
                        },
                        new
                        {
                            ID = 9,
                            DatePlaced = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4438),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 149.85m,
                            UserID = 9
                        },
                        new
                        {
                            ID = 10,
                            DatePlaced = new DateTime(2025, 1, 27, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4440),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 29.97m,
                            UserID = 10
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("CostPerUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("EquipmentID1")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("EquipmentID1");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 27, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4501),
                            EquipmentID = 1,
                            OrderID = 1,
                            Price = 5.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 26, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4497)
                        },
                        new
                        {
                            ID = 2,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 28, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4506),
                            EquipmentID = 3,
                            OrderID = 1,
                            Price = 4.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 26, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4505)
                        },
                        new
                        {
                            ID = 3,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 29, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4509),
                            EquipmentID = 2,
                            OrderID = 2,
                            Price = 10.47m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 28, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4508)
                        },
                        new
                        {
                            ID = 4,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4513),
                            EquipmentID = 1,
                            OrderID = 2,
                            Price = 11.96m,
                            Quantity = 4,
                            StartDate = new DateTime(2025, 1, 28, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4511)
                        },
                        new
                        {
                            ID = 5,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4516),
                            EquipmentID = 3,
                            OrderID = 3,
                            Price = 9.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4515)
                        },
                        new
                        {
                            ID = 6,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4520),
                            EquipmentID = 1,
                            OrderID = 4,
                            Price = 2.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 29, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4519)
                        },
                        new
                        {
                            ID = 7,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4523),
                            EquipmentID = 2,
                            OrderID = 5,
                            Price = 17.45m,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4522)
                        },
                        new
                        {
                            ID = 8,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4526),
                            EquipmentID = 3,
                            OrderID = 6,
                            Price = 14.97m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4525)
                        },
                        new
                        {
                            ID = 9,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 2, 6, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4528),
                            EquipmentID = 1,
                            OrderID = 7,
                            Price = 5.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4527)
                        },
                        new
                        {
                            ID = 10,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4532),
                            EquipmentID = 2,
                            OrderID = 8,
                            Price = 10.47m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4531)
                        },
                        new
                        {
                            ID = 11,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4539),
                            EquipmentID = 3,
                            OrderID = 9,
                            Price = 4.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4537)
                        },
                        new
                        {
                            ID = 12,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4542),
                            EquipmentID = 1,
                            OrderID = 9,
                            Price = 14.95m,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4541)
                        },
                        new
                        {
                            ID = 13,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 28, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4544),
                            EquipmentID = 2,
                            OrderID = 10,
                            Price = 6.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 27, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4543)
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NumberOfStars")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderItemID")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2025, 1, 27, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4601),
                            Description = "Great quality and very durable!",
                            IsDeleted = false,
                            NumberOfStars = 4.5m,
                            OrderItemID = 1
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2025, 1, 28, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4619),
                            Description = "Not as expected, could be better.",
                            IsDeleted = false,
                            NumberOfStars = 2.0m,
                            OrderItemID = 2
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2025, 1, 29, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4622),
                            Description = "Perfect for my needs, highly recommended!",
                            IsDeleted = false,
                            NumberOfStars = 5.0m,
                            OrderItemID = 3
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2025, 1, 30, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4623),
                            Description = "Good value for the price.",
                            IsDeleted = false,
                            NumberOfStars = 4.0m,
                            OrderItemID = 4
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2025, 1, 31, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4625),
                            Description = "Satisfactory but delivery was delayed.",
                            IsDeleted = false,
                            NumberOfStars = 3.0m,
                            OrderItemID = 5
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2025, 2, 1, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4627),
                            Description = "Excellent performance and quality.",
                            IsDeleted = false,
                            NumberOfStars = 5.0m,
                            OrderItemID = 6
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2025, 2, 2, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4630),
                            Description = "Decent product but could use some improvements.",
                            IsDeleted = false,
                            NumberOfStars = 3.5m,
                            OrderItemID = 7
                        },
                        new
                        {
                            ID = 8,
                            DateAdded = new DateTime(2025, 2, 3, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4631),
                            Description = "Very satisfied with the purchase.",
                            IsDeleted = false,
                            NumberOfStars = 4.5m,
                            OrderItemID = 8
                        },
                        new
                        {
                            ID = 9,
                            DateAdded = new DateTime(2025, 2, 4, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4633),
                            Description = "The item was okay, nothing special.",
                            IsDeleted = false,
                            NumberOfStars = 3.0m,
                            OrderItemID = 9
                        },
                        new
                        {
                            ID = 10,
                            DateAdded = new DateTime(2025, 2, 5, 21, 4, 58, 307, DateTimeKind.Local).AddTicks(4635),
                            Description = "Amazing product! Will buy again.",
                            IsDeleted = false,
                            NumberOfStars = 5.0m,
                            OrderItemID = 10
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Radnik u rent biznisu, koristi desktop app",
                            Name = "employee"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Krajnji korisnik, koristi mobilnu aplikaciju",
                            Name = "end-user"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "una.belko+radnik@edu.fit.ba",
                            FirstName = "Una",
                            IsActive = true,
                            LastName = "Radnik",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "0038763222111",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 2,
                            Email = "una.belko+shopping@edu.fit.ba",
                            FirstName = "Una",
                            IsActive = true,
                            LastName = "Shopping",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "0038763222111",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 3,
                            Email = "michael.johnson+user@rental.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-8765",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 4,
                            Email = "emily.davis+user@rental.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-4321",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 5,
                            Email = "william.brown+user@rental.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-6789",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 6,
                            Email = "ava.wilson+user@rental.com",
                            FirstName = "Ava",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-2345",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 7,
                            Email = "james.taylor+user@rental.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-7890",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 8,
                            Email = "olivia.anderson+user@rental.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-3456",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 9,
                            Email = "benjamin.thomas+user@rental.com",
                            FirstName = "Benjamin",
                            IsActive = true,
                            LastName = "Thomas",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-9012",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        },
                        new
                        {
                            ID = 10,
                            Email = "sophia.moore+user@rental.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "LN6gh3VQQyuhR3i4WgSqgkrNLNXTqZBCSa11ladbSNs=",
                            Phone = "555-6543",
                            Salt = "ghyprCsz4gkzTGQhAQOzUw=="
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            UserID = 2,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 3,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 4,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 5,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 6,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 7,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 8,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 9,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 10,
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.CartItem", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", null)
                        .WithMany("CartItems")
                        .HasForeignKey("EquipmentID1");

                    b.Navigation("Cart");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Damage", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.OrderItem", "OrderItem")
                        .WithMany("Damages")
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "AddedByUser")
                        .WithMany("Equipment")
                        .HasForeignKey("AddedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.EquipmentCategory", "EquipmentCategory")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentCategoryId");

                    b.HasOne("rs2_rent_sistem.Services.Database.Manufacturer", "Manufacturer")
                        .WithMany("Equipment")
                        .HasForeignKey("ManufacturerID");

                    b.Navigation("AddedByUser");

                    b.Navigation("EquipmentCategory");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("EquipmentID1");

                    b.HasOne("rs2_rent_sistem.Services.Database.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Review", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.OrderItem", "OrderItem")
                        .WithOne("Review")
                        .HasForeignKey("rs2_rent_sistem.Services.Database.Review", "OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.UserRole", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Manufacturer", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.Navigation("Damages");

                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Equipment");

                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
