// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rs2_rent_sistem.Services.Data;

#nullable disable

namespace rs2_rent_sistem.Services.Migrations
{
    [DbContext(typeof(RentSistemDbContext))]
    partial class RentSistemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2525),
                            TotalPrice = 45.75m,
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2528),
                            TotalPrice = 120.00m,
                            UserID = 3
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2531),
                            TotalPrice = 65.30m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2532),
                            TotalPrice = 78.40m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2534),
                            TotalPrice = 52.10m,
                            UserID = 6
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2536),
                            TotalPrice = 98.25m,
                            UserID = 7
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2538),
                            TotalPrice = 36.60m,
                            UserID = 8
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("EquipmentID1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("EquipmentID1");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CartID = 1,
                            EndDate = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2591),
                            EquipmentID = 1,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2589)
                        },
                        new
                        {
                            ID = 2,
                            CartID = 1,
                            EndDate = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2595),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2594)
                        },
                        new
                        {
                            ID = 3,
                            CartID = 2,
                            EndDate = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2598),
                            EquipmentID = 3,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2596)
                        },
                        new
                        {
                            ID = 4,
                            CartID = 3,
                            EndDate = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2600),
                            EquipmentID = 1,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2599)
                        },
                        new
                        {
                            ID = 5,
                            CartID = 3,
                            EndDate = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2602),
                            EquipmentID = 2,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2601)
                        },
                        new
                        {
                            ID = 6,
                            CartID = 4,
                            EndDate = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2606),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2605)
                        },
                        new
                        {
                            ID = 7,
                            CartID = 4,
                            EndDate = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2608),
                            EquipmentID = 3,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2607)
                        },
                        new
                        {
                            ID = 8,
                            CartID = 5,
                            EndDate = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2610),
                            EquipmentID = 1,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2609)
                        },
                        new
                        {
                            ID = 9,
                            CartID = 6,
                            EndDate = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2613),
                            EquipmentID = 3,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2612)
                        },
                        new
                        {
                            ID = 10,
                            CartID = 7,
                            EndDate = new DateTime(2025, 2, 5, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2615),
                            EquipmentID = 2,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2614)
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Damage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Damages");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPerUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("int");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddedByUserID");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedByUserID = 1,
                            CostPerUse = 2.99m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1572),
                            Description = "Official size and weight.",
                            EquipmentCategoryId = 1,
                            ImageUrl = "soccerball.jpg",
                            IsDeleted = false,
                            ItemName = "Soccer Ball",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            ID = 2,
                            AddedByUserID = 1,
                            CostPerUse = 3.49m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1610),
                            Description = "High-quality leather basketball.",
                            EquipmentCategoryId = 2,
                            ImageUrl = "basketball.jpg",
                            IsDeleted = false,
                            ItemName = "Basketball",
                            ManufacturerID = 2,
                            MaxQuantity = 40,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 3,
                            AddedByUserID = 1,
                            CostPerUse = 4.99m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1613),
                            Description = "Lightweight racket for professional use.",
                            EquipmentCategoryId = 3,
                            ImageUrl = "tennisracket.jpg",
                            IsDeleted = false,
                            ItemName = "Tennis Racket",
                            ManufacturerID = 3,
                            MaxQuantity = 25,
                            MinQuantity = 2,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 4,
                            AddedByUserID = 1,
                            CostPerUse = 6.99m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1682),
                            Description = "Description for Equipment 4",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment4.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 4",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 19
                        },
                        new
                        {
                            ID = 5,
                            AddedByUserID = 1,
                            CostPerUse = 4.08m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1693),
                            Description = "Description for Equipment 5",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment5.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 5",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 19
                        },
                        new
                        {
                            ID = 6,
                            AddedByUserID = 1,
                            CostPerUse = 4.81m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1703),
                            Description = "Description for Equipment 6",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment6.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 6",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 35
                        },
                        new
                        {
                            ID = 7,
                            AddedByUserID = 1,
                            CostPerUse = 6.79m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1712),
                            Description = "Description for Equipment 7",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment7.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 7",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 31
                        },
                        new
                        {
                            ID = 8,
                            AddedByUserID = 1,
                            CostPerUse = 4.31m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1746),
                            Description = "Description for Equipment 8",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment8.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 8",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 23
                        },
                        new
                        {
                            ID = 9,
                            AddedByUserID = 1,
                            CostPerUse = 0.95m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1819),
                            Description = "Description for Equipment 9",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment9.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 9",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 36
                        },
                        new
                        {
                            ID = 10,
                            AddedByUserID = 1,
                            CostPerUse = 5.59m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1829),
                            Description = "Description for Equipment 10",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment10.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 10",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 13
                        },
                        new
                        {
                            ID = 11,
                            AddedByUserID = 1,
                            CostPerUse = 2.74m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1839),
                            Description = "Description for Equipment 11",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment11.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 11",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 35
                        },
                        new
                        {
                            ID = 12,
                            AddedByUserID = 1,
                            CostPerUse = 0.41m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1847),
                            Description = "Description for Equipment 12",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment12.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 12",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 46
                        },
                        new
                        {
                            ID = 13,
                            AddedByUserID = 1,
                            CostPerUse = 7.97m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1856),
                            Description = "Description for Equipment 13",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment13.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 13",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 14,
                            AddedByUserID = 1,
                            CostPerUse = 3.62m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1864),
                            Description = "Description for Equipment 14",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment14.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 14",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 33
                        },
                        new
                        {
                            ID = 15,
                            AddedByUserID = 1,
                            CostPerUse = 6.39m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1873),
                            Description = "Description for Equipment 15",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment15.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 15",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        },
                        new
                        {
                            ID = 16,
                            AddedByUserID = 1,
                            CostPerUse = 3.17m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1881),
                            Description = "Description for Equipment 16",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment16.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 16",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 28
                        },
                        new
                        {
                            ID = 17,
                            AddedByUserID = 1,
                            CostPerUse = 4.72m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1889),
                            Description = "Description for Equipment 17",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment17.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 17",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 21
                        },
                        new
                        {
                            ID = 18,
                            AddedByUserID = 1,
                            CostPerUse = 6.64m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1899),
                            Description = "Description for Equipment 18",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment18.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 18",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 28
                        },
                        new
                        {
                            ID = 19,
                            AddedByUserID = 1,
                            CostPerUse = 0.21m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1945),
                            Description = "Description for Equipment 19",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment19.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 19",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 49
                        },
                        new
                        {
                            ID = 20,
                            AddedByUserID = 1,
                            CostPerUse = 2.70m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1954),
                            Description = "Description for Equipment 20",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment20.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 20",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 31
                        },
                        new
                        {
                            ID = 21,
                            AddedByUserID = 1,
                            CostPerUse = 3.56m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1962),
                            Description = "Description for Equipment 21",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment21.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 21",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 13
                        },
                        new
                        {
                            ID = 22,
                            AddedByUserID = 1,
                            CostPerUse = 4.34m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1970),
                            Description = "Description for Equipment 22",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment22.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 22",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 23,
                            AddedByUserID = 1,
                            CostPerUse = 9.30m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1979),
                            Description = "Description for Equipment 23",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment23.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 23",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 45
                        },
                        new
                        {
                            ID = 24,
                            AddedByUserID = 1,
                            CostPerUse = 5.03m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1987),
                            Description = "Description for Equipment 24",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment24.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 24",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 29
                        },
                        new
                        {
                            ID = 25,
                            AddedByUserID = 1,
                            CostPerUse = 9.46m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(1995),
                            Description = "Description for Equipment 25",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment25.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 25",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 26,
                            AddedByUserID = 1,
                            CostPerUse = 6.88m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2003),
                            Description = "Description for Equipment 26",
                            EquipmentCategoryId = 1,
                            ImageUrl = "equipment26.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 26",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 36
                        },
                        new
                        {
                            ID = 27,
                            AddedByUserID = 1,
                            CostPerUse = 3.01m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2011),
                            Description = "Description for Equipment 27",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment27.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 27",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 14
                        },
                        new
                        {
                            ID = 28,
                            AddedByUserID = 1,
                            CostPerUse = 7.71m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2019),
                            Description = "Description for Equipment 28",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment28.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 28",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 13
                        },
                        new
                        {
                            ID = 29,
                            AddedByUserID = 1,
                            CostPerUse = 4.38m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2027),
                            Description = "Description for Equipment 29",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment29.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 29",
                            ManufacturerID = 3,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 30,
                            AddedByUserID = 1,
                            CostPerUse = 0.91m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2036),
                            Description = "Description for Equipment 30",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment30.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 30",
                            ManufacturerID = 7,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 16
                        },
                        new
                        {
                            ID = 31,
                            AddedByUserID = 1,
                            CostPerUse = 4.26m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2075),
                            Description = "Description for Equipment 31",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment31.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 31",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 32
                        },
                        new
                        {
                            ID = 32,
                            AddedByUserID = 1,
                            CostPerUse = 6.04m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2084),
                            Description = "Description for Equipment 32",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment32.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 32",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 10
                        },
                        new
                        {
                            ID = 33,
                            AddedByUserID = 1,
                            CostPerUse = 8.41m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2092),
                            Description = "Description for Equipment 33",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment33.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 33",
                            ManufacturerID = 2,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 11
                        },
                        new
                        {
                            ID = 34,
                            AddedByUserID = 1,
                            CostPerUse = 6.54m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2102),
                            Description = "Description for Equipment 34",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment34.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 34",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 35,
                            AddedByUserID = 1,
                            CostPerUse = 0.62m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2110),
                            Description = "Description for Equipment 35",
                            EquipmentCategoryId = 2,
                            ImageUrl = "equipment35.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 35",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 20
                        },
                        new
                        {
                            ID = 36,
                            AddedByUserID = 1,
                            CostPerUse = 6.17m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2118),
                            Description = "Description for Equipment 36",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment36.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 36",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 28
                        },
                        new
                        {
                            ID = 37,
                            AddedByUserID = 1,
                            CostPerUse = 5.40m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2126),
                            Description = "Description for Equipment 37",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment37.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 37",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 18
                        },
                        new
                        {
                            ID = 38,
                            AddedByUserID = 1,
                            CostPerUse = 5.53m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2133),
                            Description = "Description for Equipment 38",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment38.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 38",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 15
                        },
                        new
                        {
                            ID = 39,
                            AddedByUserID = 1,
                            CostPerUse = 3.34m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2142),
                            Description = "Description for Equipment 39",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment39.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 39",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 22
                        },
                        new
                        {
                            ID = 40,
                            AddedByUserID = 1,
                            CostPerUse = 7.31m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2150),
                            Description = "Description for Equipment 40",
                            EquipmentCategoryId = 6,
                            ImageUrl = "equipment40.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 40",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 33
                        },
                        new
                        {
                            ID = 41,
                            AddedByUserID = 1,
                            CostPerUse = 4.62m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2184),
                            Description = "Description for Equipment 41",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment41.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 41",
                            ManufacturerID = 5,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 11
                        },
                        new
                        {
                            ID = 42,
                            AddedByUserID = 1,
                            CostPerUse = 1.69m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2192),
                            Description = "Description for Equipment 42",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment42.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 42",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 38
                        },
                        new
                        {
                            ID = 43,
                            AddedByUserID = 1,
                            CostPerUse = 7.49m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2200),
                            Description = "Description for Equipment 43",
                            EquipmentCategoryId = 7,
                            ImageUrl = "equipment43.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 43",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 10
                        },
                        new
                        {
                            ID = 44,
                            AddedByUserID = 1,
                            CostPerUse = 8.86m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2208),
                            Description = "Description for Equipment 44",
                            EquipmentCategoryId = 9,
                            ImageUrl = "equipment44.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 44",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 45,
                            AddedByUserID = 1,
                            CostPerUse = 7.98m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2216),
                            Description = "Description for Equipment 45",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment45.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 45",
                            ManufacturerID = 4,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 39
                        },
                        new
                        {
                            ID = 46,
                            AddedByUserID = 1,
                            CostPerUse = 0.06m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2224),
                            Description = "Description for Equipment 46",
                            EquipmentCategoryId = 5,
                            ImageUrl = "equipment46.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 46",
                            ManufacturerID = 1,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 33
                        },
                        new
                        {
                            ID = 47,
                            AddedByUserID = 1,
                            CostPerUse = 5.26m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2232),
                            Description = "Description for Equipment 47",
                            EquipmentCategoryId = 8,
                            ImageUrl = "equipment47.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 47",
                            ManufacturerID = 6,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 27
                        },
                        new
                        {
                            ID = 48,
                            AddedByUserID = 1,
                            CostPerUse = 5.34m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2240),
                            Description = "Description for Equipment 48",
                            EquipmentCategoryId = 4,
                            ImageUrl = "equipment48.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 48",
                            ManufacturerID = 8,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 45
                        },
                        new
                        {
                            ID = 49,
                            AddedByUserID = 1,
                            CostPerUse = 4.35m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2248),
                            Description = "Description for Equipment 49",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment49.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 49",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 14
                        },
                        new
                        {
                            ID = 50,
                            AddedByUserID = 1,
                            CostPerUse = 0.77m,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2256),
                            Description = "Description for Equipment 50",
                            EquipmentCategoryId = 3,
                            ImageUrl = "equipment50.jpg",
                            IsDeleted = false,
                            ItemName = "Equipment 50",
                            ManufacturerID = 9,
                            MaxQuantity = 50,
                            MinQuantity = 5,
                            StockQuantity = 44
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.EquipmentCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EquipmentCategories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Equipment for football and soccer",
                            IsDeleted = false,
                            Name = "Football"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Basketball equipment and accessories",
                            IsDeleted = false,
                            Name = "Basketball"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Tennis rackets and gear",
                            IsDeleted = false,
                            Name = "Tennis"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Baseball bats, gloves, and equipment",
                            IsDeleted = false,
                            Name = "Baseball"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Bikes and cycling gear",
                            IsDeleted = false,
                            Name = "Cycling"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Running shoes and accessories",
                            IsDeleted = false,
                            Name = "Running"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Swimming gear and equipment",
                            IsDeleted = false,
                            Name = "Swimming"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Golf clubs and accessories",
                            IsDeleted = false,
                            Name = "Golf"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Boxing gloves and equipment",
                            IsDeleted = false,
                            Name = "Boxing"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Fitness and gym equipment",
                            IsDeleted = false,
                            Name = "Fitness"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Sportswear and equipment manufacturer",
                            IsDeleted = false,
                            Name = "Nike"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Global sports equipment manufacturer",
                            IsDeleted = false,
                            Name = "Adidas"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Sporting goods and apparel manufacturer",
                            IsDeleted = false,
                            Name = "Puma"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Performance apparel and gear",
                            IsDeleted = false,
                            Name = "Under Armour"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Footwear and sports equipment",
                            IsDeleted = false,
                            Name = "Reebok"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Sports equipment, especially in tennis",
                            IsDeleted = false,
                            Name = "Wilson"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Basketball and sporting goods manufacturer",
                            IsDeleted = false,
                            Name = "Spalding"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Badminton and tennis equipment manufacturer",
                            IsDeleted = false,
                            Name = "Yonex"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Golf equipment and accessories",
                            IsDeleted = false,
                            Name = "Callaway"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Boxing equipment and apparel manufacturer",
                            IsDeleted = false,
                            Name = "Everlast"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatePlaced")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DatePlaced = new DateTime(2025, 1, 25, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2355),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 59.94m,
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            DatePlaced = new DateTime(2025, 1, 27, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2358),
                            IsActive = true,
                            Status = "paid",
                            TotalPrice = 89.85m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            DatePlaced = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2360),
                            IsActive = true,
                            Status = "rented",
                            TotalPrice = 29.97m,
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            DatePlaced = new DateTime(2025, 1, 28, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2362),
                            IsActive = true,
                            Status = "rented",
                            TotalPrice = 19.98m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            DatePlaced = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2363),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 99.90m,
                            UserID = 5
                        },
                        new
                        {
                            ID = 6,
                            DatePlaced = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2365),
                            IsActive = true,
                            Status = "rented",
                            TotalPrice = 49.95m,
                            UserID = 6
                        },
                        new
                        {
                            ID = 7,
                            DatePlaced = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2367),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 69.93m,
                            UserID = 7
                        },
                        new
                        {
                            ID = 8,
                            DatePlaced = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2369),
                            IsActive = true,
                            Status = "paid",
                            TotalPrice = 39.96m,
                            UserID = 8
                        },
                        new
                        {
                            ID = 9,
                            DatePlaced = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2370),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 149.85m,
                            UserID = 9
                        },
                        new
                        {
                            ID = 10,
                            DatePlaced = new DateTime(2025, 1, 26, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2372),
                            IsActive = true,
                            Status = "returned",
                            TotalPrice = 29.97m,
                            UserID = 10
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("CostPerUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("EquipmentID1")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("EquipmentID1");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 26, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2424),
                            EquipmentID = 1,
                            OrderID = 1,
                            Price = 5.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 25, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2419)
                        },
                        new
                        {
                            ID = 2,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 27, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2429),
                            EquipmentID = 3,
                            OrderID = 1,
                            Price = 4.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 25, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2427)
                        },
                        new
                        {
                            ID = 3,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 28, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2432),
                            EquipmentID = 2,
                            OrderID = 2,
                            Price = 10.47m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 1, 27, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2431)
                        },
                        new
                        {
                            ID = 4,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2435),
                            EquipmentID = 1,
                            OrderID = 2,
                            Price = 11.96m,
                            Quantity = 4,
                            StartDate = new DateTime(2025, 1, 27, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2434)
                        },
                        new
                        {
                            ID = 5,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2439),
                            EquipmentID = 3,
                            OrderID = 3,
                            Price = 9.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2438)
                        },
                        new
                        {
                            ID = 6,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2443),
                            EquipmentID = 1,
                            OrderID = 4,
                            Price = 2.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 28, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2442)
                        },
                        new
                        {
                            ID = 7,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2446),
                            EquipmentID = 2,
                            OrderID = 5,
                            Price = 17.45m,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2445)
                        },
                        new
                        {
                            ID = 8,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2449),
                            EquipmentID = 3,
                            OrderID = 6,
                            Price = 14.97m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2448)
                        },
                        new
                        {
                            ID = 9,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 2, 5, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2452),
                            EquipmentID = 1,
                            OrderID = 7,
                            Price = 5.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2451)
                        },
                        new
                        {
                            ID = 10,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2455),
                            EquipmentID = 2,
                            OrderID = 8,
                            Price = 10.47m,
                            Quantity = 3,
                            StartDate = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2454)
                        },
                        new
                        {
                            ID = 11,
                            CostPerUse = 4.99m,
                            EndDate = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2458),
                            EquipmentID = 3,
                            OrderID = 9,
                            Price = 4.99m,
                            Quantity = 1,
                            StartDate = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2457)
                        },
                        new
                        {
                            ID = 12,
                            CostPerUse = 2.99m,
                            EndDate = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2461),
                            EquipmentID = 1,
                            OrderID = 9,
                            Price = 14.95m,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2460)
                        },
                        new
                        {
                            ID = 13,
                            CostPerUse = 3.49m,
                            EndDate = new DateTime(2025, 1, 27, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2464),
                            EquipmentID = 2,
                            OrderID = 10,
                            Price = 6.98m,
                            Quantity = 2,
                            StartDate = new DateTime(2025, 1, 26, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2463)
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NumberOfStars")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2025, 1, 26, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2490),
                            Description = "Great quality and very durable!",
                            IsDeleted = false,
                            NumberOfStars = 4.5m,
                            OrderItemID = 1
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2025, 1, 27, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2494),
                            Description = "Not as expected, could be better.",
                            IsDeleted = false,
                            NumberOfStars = 2.0m,
                            OrderItemID = 2
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2025, 1, 28, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2496),
                            Description = "Perfect for my needs, highly recommended!",
                            IsDeleted = false,
                            NumberOfStars = 5.0m,
                            OrderItemID = 3
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2025, 1, 29, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2498),
                            Description = "Good value for the price.",
                            IsDeleted = false,
                            NumberOfStars = 4.0m,
                            OrderItemID = 4
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2025, 1, 30, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2500),
                            Description = "Satisfactory but delivery was delayed.",
                            IsDeleted = false,
                            NumberOfStars = 3.0m,
                            OrderItemID = 5
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2025, 1, 31, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2502),
                            Description = "Excellent performance and quality.",
                            IsDeleted = false,
                            NumberOfStars = 5.0m,
                            OrderItemID = 6
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2025, 2, 1, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2504),
                            Description = "Decent product but could use some improvements.",
                            IsDeleted = false,
                            NumberOfStars = 3.5m,
                            OrderItemID = 7
                        },
                        new
                        {
                            ID = 8,
                            DateAdded = new DateTime(2025, 2, 2, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2506),
                            Description = "Very satisfied with the purchase.",
                            IsDeleted = false,
                            NumberOfStars = 4.5m,
                            OrderItemID = 8
                        },
                        new
                        {
                            ID = 9,
                            DateAdded = new DateTime(2025, 2, 3, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2507),
                            Description = "The item was okay, nothing special.",
                            IsDeleted = false,
                            NumberOfStars = 3.0m,
                            OrderItemID = 9
                        },
                        new
                        {
                            ID = 10,
                            DateAdded = new DateTime(2025, 2, 4, 20, 1, 25, 285, DateTimeKind.Local).AddTicks(2510),
                            Description = "Amazing product! Will buy again.",
                            IsDeleted = false,
                            NumberOfStars = 5.0m,
                            OrderItemID = 10
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Radnik u rent biznisu, koristi desktop app",
                            Name = "employee"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Krajnji korisnik, koristi mobilnu aplikaciju",
                            Name = "end-user"
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "una.belko+radnik@edu.fit.ba",
                            FirstName = "Una",
                            IsActive = true,
                            LastName = "Radnik",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "0038763222111",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 2,
                            Email = "una.belko+shopping@edu.fit.ba",
                            FirstName = "Una",
                            IsActive = true,
                            LastName = "Shopping",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "0038763222111",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 3,
                            Email = "michael.johnson+user@rental.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-8765",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 4,
                            Email = "emily.davis+user@rental.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-4321",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 5,
                            Email = "william.brown+user@rental.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-6789",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 6,
                            Email = "ava.wilson+user@rental.com",
                            FirstName = "Ava",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-2345",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 7,
                            Email = "james.taylor+user@rental.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-7890",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 8,
                            Email = "olivia.anderson+user@rental.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-3456",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 9,
                            Email = "benjamin.thomas+user@rental.com",
                            FirstName = "Benjamin",
                            IsActive = true,
                            LastName = "Thomas",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-9012",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        },
                        new
                        {
                            ID = 10,
                            Email = "sophia.moore+user@rental.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "Ljzw8HnfiYwhMbO7vJnnfurD/X8Z3rZ9tDO+5IO+hH8=",
                            Phone = "555-6543",
                            Salt = "gfemRTdJWjVykCcD25n+iw=="
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            UserID = 2,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 3,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 4,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 5,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 6,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 7,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 8,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 9,
                            RoleID = 2
                        },
                        new
                        {
                            UserID = 10,
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.CartItem", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", null)
                        .WithMany("CartItems")
                        .HasForeignKey("EquipmentID1");

                    b.Navigation("Cart");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Damage", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.OrderItem", "OrderItem")
                        .WithMany("Damages")
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "AddedByUser")
                        .WithMany("Equipment")
                        .HasForeignKey("AddedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.EquipmentCategory", "EquipmentCategory")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentCategoryId");

                    b.HasOne("rs2_rent_sistem.Services.Database.Manufacturer", "Manufacturer")
                        .WithMany("Equipment")
                        .HasForeignKey("ManufacturerID");

                    b.Navigation("AddedByUser");

                    b.Navigation("EquipmentCategory");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.Equipment", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("EquipmentID1");

                    b.HasOne("rs2_rent_sistem.Services.Database.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Review", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.UserRole", b =>
                {
                    b.HasOne("rs2_rent_sistem.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rs2_rent_sistem.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Equipment", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Manufacturer", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.OrderItem", b =>
                {
                    b.Navigation("Damages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("rs2_rent_sistem.Services.Database.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Equipment");

                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
